# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-for-cluster-service
spec:
  selector:
    matchLabels:
      app: apache
      env: dev
      tag: cluster-service
  replicas: 2

# pod creation
  template:
    metadata:
      name: apache-pods
      labels:
        app: apache
        env: dev
        tag: cluster-service
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cluster-service
# spec:
#   type: ClusterIP
#   selector:
#     app: apache
#     env: dev
#     tag: cluster-service
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 80